inherit_from: .rubocop_todo.yml
require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: disable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'lib/tasks/auto_annotate_models.rake'
    - 'Guardfile'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  EnforcedStyle: expanded